import React from "react";

const PrivacyPolicy = () => {
  return (
    <div className="mt-24 mx-24 text-white">
      <h1 className="text-3xl font-bold mb-6 text-white">
        Privacy Policy for Fendous AI (Subsidiary of Fendous Sustainable Solutions)
      </h1>
      <p>
        <strong>Effective Date: February 18, 2025</strong>
      </p>

      <section className="mb-6">
        <h2 className="text-2xl font-bold mb-4">1. Data Controller</h2>
        <p>
          We are the data controller for the personal data we process about our customers and partners. Fendous AI (subsidiary of Fendous Sustainable Solutions) focuses on AI-driven products, including Fendous AI chatbots.
        </p>
        <p>
          <strong>Address:</strong> Valdermarsgade 8 1 TV, 9000 Aalborg, Denmark<br />
          <strong>CVR No.:</strong> 43257196
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-bold mb-4">2. Interpretation and Definitions</h2>
        <h3 className="text-xl font-semibold mb-2">2.1 Interpretation</h3>
        <ul className="list-disc list-inside mb-4">
          <li>Words with capitalized initials have meanings as defined in this section.</li>
          <li>These definitions apply whether the terms appear in singular or plural form.</li>
        </ul>
        <h3 className="text-xl font-semibold mb-2">2.2 Definitions</h3>
        <ul className="list-disc list-inside mb-4">
          <li><strong>Account</strong> – A unique account created for You to access our Service or parts of our Service.</li>
          <li><strong>Affiliate</strong> – Any entity that controls, is controlled by, or is under common control with a party. "Control" means ownership of 50% or more of shares, equity interests, or other securities that allow voting rights for managing authority.</li>
          <li><strong>Application</strong> – Refers to Fendous AI, the software program provided by the Company.</li>
          <li><strong>Company ("We", "Us", or "Our")</strong> – Refers to Fendous Sustainable Solutions ApS, located at Valdermarsgade 8 1 TV, 9000 Aalborg, Denmark.</li>
          <li><strong>Cookies</strong> – Small files placed on Your device (computer, mobile, or tablet) by a website to store browsing history and enhance user experience.</li>
          <li><strong>Country</strong> – Refers to Denmark.</li>
          <li><strong>Device</strong> – Any device that can access the Service, such as a computer, cellphone, or digital tablet.</li>
          <li><strong>Personal Data</strong> – Any information that identifies or relates to an individual.</li>
          <li><strong>Product</strong> – Refers to the AI-based solutions, including chatbots, provided by Fendous AI.</li>
          <li><strong>Service Provider</strong> – A third-party entity that processes data on behalf of the Company, including those facilitating, analyzing, or providing the Service.</li>
          <li><strong>Third-Party Social Media Service</strong> – Any social media or external service that allows Users to log in or create an account to use the Service.</li>
          <li><strong>Usage Data</strong> – Automatically collected data, including those generated by Service usage or infrastructure (e.g., page visit duration).</li>
          <li><strong>Website</strong> – Refers to Fendous AI, accessible from:
            <ul className="list-disc list-inside ml-6">
              <li>https://www.fendousai.com</li>
              <li>www.fendous.eu</li>
            </ul>
          </li>
          <li><strong>You</strong> – The individual accessing or using the Service, or the company/legal entity on behalf of which the individual is acting.</li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-bold mb-4">3. Introduction</h2>
        <p>
          We value your privacy and are committed to protecting your personal data. This Privacy Policy explains how we collect, use, share, store, and protect your information when you use our AI-driven products. We also describe the legal bases for our processing under the GDPR.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-bold mb-4">4. Processing Activities and Information We Collect</h2>
        <h3 className="text-xl font-semibold mb-2">4.1 Website Visits</h3>
        <ul className="list-disc list-inside mb-4">
          <li><strong>Tracking Technologies and Cookies:</strong> We use cookies and similar tracking technologies to track activity on our Service and store certain information.</li>
          <li><strong>Types of Cookies We Use:</strong>
            <ul className="list-disc list-inside ml-6">
              <li><strong>Necessary Cookies:</strong> Used to authenticate users and prevent fraudulent account use.</li>
              <li><strong>Web Beacons:</strong> Electronic files (clear gifs, pixel tags) used to count visitors and track engagement.</li>
              <li><strong>Functionality Cookies:</strong> Store user preferences such as language settings.</li>
              <li><strong>Analytical Cookies:</strong> Help us analyze website traffic and user behavior.</li>
              <li><strong>Other Cookies:</strong> Unclassified cookies that may serve additional purposes.</li>
            </ul>
          </li>
        </ul>

        <h3 className="text-xl font-semibold mb-2">4.2 Communication with Potential Customers</h3>
        <ul className="list-disc list-inside mb-4">
          <li><strong>Contact Methods:</strong> When you contact us via our contact form, email, or telephone, we process the information you provide (e.g., your name, email, and phone number) to respond to your inquiries about our services.</li>
          <li><strong>Legal Basis:</strong> Processing is based on our legitimate interest (GDPR Article 6(1)(f)).</li>
          <li><strong>Retention:</strong> We delete this communication data once it is clear whether you wish to use our services—unless a longer retention period is justified.</li>
        </ul>

        <h3 className="text-xl font-semibold mb-2">4.3 Customers</h3>
        <ul className="list-disc list-inside mb-4">
          <li><strong>Service Delivery:</strong> For the proper delivery of our services, we may process personal data such as your name, address, details of services provided, special agreements, IP addresses, cookie identifiers, biometric data (e.g., facial recognition and fingerprint scans), and payment information.</li>
          <li><strong>Legal Basis:</strong> This processing is necessary for the performance of a contract (GDPR Article 6(1)(b)).</li>
          <li><strong>Retention:</strong> After the service is delivered and any outstanding issues are resolved, your data is promptly deleted.</li>
        </ul>

        <h3 className="text-xl font-semibold mb-2">4.4 Newsletter</h3>
        <ul className="list-disc list-inside mb-4">
          <li><strong>Subscription:</strong> Our newsletter is subscription-based. You receive emails with updates, new content, or service announcements only if you have given your explicit consent.</li>
          <li><strong>Legal Basis:</strong> The processing of your email address for the newsletter is based on your consent (GDPR Article 6(1)(a)).</li>
          <li><strong>Retention:</strong> We retain your data as long as you are subscribed. In case of unsubscription, we cease sending newsletters and maintain a record of your consent for 2 years (in line with applicable retention rules).</li>
        </ul>

        <h3 className="text-xl font-semibold mb-2">4.5 Accounting</h3>
        <ul className="list-disc list-inside mb-4">
          <li><strong>Invoices and Financial Records:</strong> In compliance with accounting law, we store invoices and similar documents that may contain personal data (e.g., name, address, service description).</li>
          <li><strong>Legal Basis:</strong> Processing is required for compliance with a legal obligation (GDPR Article 6(1)(c)).</li>
          <li><strong>Retention:</strong> These records are stored for a minimum of 5 years after the end of the relevant financial year.</li>
        </ul>

        <h3 className="text-xl font-semibold mb-2">4.6 Job Applications</h3>
        <ul className="list-disc list-inside mb-4">
          <li><strong>Recruitment Process:</strong> When you apply for a job, we process your application data to assess your suitability for a position. For unsolicited applications, your data is reviewed and, if not relevant, deleted immediately. For advertised positions, if you are not selected, your application is deleted once the position is filled.</li>
          <li><strong>Legal Basis:</strong> Processing is based on our legitimate interest (GDPR Article 6(1)(f)).</li>
          <li><strong>Further Information:</strong> If you enter into a recruitment process or are hired, we will provide you with additional details on how your data is processed.</li>
        </ul>

        <h3 className="text-xl font-semibold mb-2">4.7 Data Processors</h3>
        <ul className="list-disc list-inside mb-4">
          <li><strong>External Providers:</strong> We work with external service providers (data processors) to support our operations—for example, IT hosting, marketing, payment processing, and analytics. These partners are contractually obligated to protect your personal data.</li>
          <li><strong>Examples:</strong>
            <ul className="list-disc list-inside ml-6">
              <li><strong>Stripe</strong> - <a href="https://stripe.com/privacy" className="text-blue-500">Privacy Policy</a></li>
              <li><strong>MobilePay</strong> - <a href="https://mobilepay.dk/app/legal/privacy-notice/en" className="text-blue-500">Privacy Policy</a></li>
            </ul>
          </li>
        </ul>

        <h3 className="text-xl font-semibold mb-2">4.8 Information from Third-Party Social Media Services</h3>
        <p>
          The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:
        </p>
        <ul className="list-disc list-inside mb-4">
          <li>Google</li>
          <li>Facebook</li>
          <li>Twitter</li>
          <li>LinkedIn</li>
          <li>Instagram</li>
          <li>YouTube</li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-bold mb-4">5. How We Use Your Personal Data</h2>
        <p>
          We use your data for various purposes, including:
        </p>
        <ul className="list-disc list-inside mb-4">
          <li><strong>AI Chatbot Interaction:</strong> Our AI-powered chatbot collects data (e.g., name, email, conversation history) to improve responses and functionality.</li>
          <li><strong>Service Provision:</strong> To provide and maintain our AI products and chatbot functionalities.</li>
          <li><strong>Payment Processing:</strong> To process transactions through secure third-party payment processors like Stripe and MobilePay.</li>
          <li><strong>Communications:</strong> To send updates, offers, and essential notifications.</li>
          <li><strong>Opt-Out Options:</strong> If you prefer not to interact with our AI chatbot, you may choose to engage with a human representative or adjust your communication preferences.</li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-bold mb-4">6. Sharing Your Personal Data</h2>
        <p>
          We do not share your personal data with third parties unless necessary for one or more of the following reasons:
        </p>
        <ul className="list-disc list-inside mb-4">
          <li><strong>Service Providers:</strong> For example, payment processors (MobilePay, Stripe) and analytics companies.</li>
          <li><strong>Third-Party Affiliates:</strong> For marketing or service purposes.</li>
          <li><strong>Other Users:</strong> When you interact publicly on our platform (e.g., comments, forum posts).</li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-bold mb-4">7. Retention and Deletion of Your Personal Data</h2>
        <ul className="list-disc list-inside mb-4">
          <li><strong>AI Chatbot Data:</strong> Retained only as long as necessary for improving our AI models.</li>
          <li><strong>Communication Data:</strong> Deleted after inquiry resolution.</li>
          <li><strong>Customer Data:</strong> Deleted promptly after service delivery and resolution of outstanding matters.</li>
          <li><strong>Newsletter Data:</strong> Retained until you unsubscribe, with consent records kept for 2 years.</li>
          <li><strong>Accounting Records:</strong> Retained for at least 5 years as required by law.</li>
        </ul>
        <p>
          You have the right to request deletion of your data, subject to any legal obligations that require longer retention.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-bold mb-4">8. Third-Party Services</h2>
        <p>
          We use third-party services for payments, analytics, hosting, and database management. These providers have their own privacy policies:
        </p>
        <ul className="list-disc list-inside mb-4">
          <li><strong>OpenAI</strong> - <a href="https://openai.com/policies/row-privacy-policy/" className="text-blue-500">Privacy Policy</a></li>
          <li><strong>MongoDB</strong> - <a href="https://www.mongodb.com/legal/privacy/privacy-policy" className="text-blue-500">Privacy Policy</a></li>
          <li><strong>Stripe</strong> - <a href="https://stripe.com/privacy" className="text-blue-500">Privacy Policy</a></li>
          <li><strong>MobilePay</strong> - <a href="https://mobilepay.dk/app/legal/privacy-notice/en" className="text-blue-500">Privacy Policy</a></li>
          <li><strong>Netlify/Vercel</strong> - <a href="https://www.netlify.com/privacy/" className="text-blue-500">Privacy Policy</a></li>
          <li><strong>Landbot</strong> - <a href="https://landbot.io/privacy-policy" className="text-blue-500">Privacy Policy</a></li>
          <li><strong>Google Places</strong> - <a href="https://policies.google.com/privacy?hl=en-US" className="text-blue-500">Privacy Policy</a></li>
          <li><strong>Caspio</strong> - <a href="https://www.caspio.com/caspio-privacy-statement/" className="text-blue-500">Privacy Policy</a></li>
          <li><strong>Mailerlite</strong> - <a href="https://www.mailerlite.com/legal/privacy-policy" className="text-blue-500">Privacy Policy</a></li>
          <li><strong>Mailjet</strong> - <a href="https://www.mailjet.com/legal/privacy-policy" className="text-blue-500">Privacy Policy</a></li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-bold mb-4">9. Your Rights Under GDPR</h2>
        <p>
          You have the following rights regarding your personal data:
        </p>
        <ul className="list-disc list-inside mb-4">
          <li><strong>Right of Access:</strong> Request access to your personal data.</li>
          <li><strong>Right to Rectification:</strong> Request corrections to any inaccurate or incomplete information.</li>
          <li><strong>Right to Erasure:</strong> Request data deletion under certain conditions.</li>
          <li><strong>Right to Restrict Processing:</strong> Request limitation on data processing.</li>
          <li><strong>Right to Object:</strong> Object to processing, including direct marketing.</li>
          <li><strong>Right to Data Portability:</strong> Request data in a structured, machine-readable format.</li>
          <li><strong>Right to Withdraw Consent:</strong> Withdraw consent at any time if processing is based on your consent.</li>
        </ul>
        <p>
          For further details about your rights, please refer to the Danish Data Protection Authority’s guidance at <a href="https://www.datatilsynet.dk" className="text-blue-500">www.datatilsynet.dk</a>.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-bold mb-4">10. Children's Privacy</h2>
        <p>
          Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. . If we become aware that we have collected Personal Data from anyone under the age of 13 without verification of parental consent, we take steps to remove that information from our servers.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-bold mb-4">11. Profiling and Automated Decisions</h2>
        <p>
        We do not engage in profiling or automated decision-making that produces legal effects or similarly significant impacts on you.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-bold mb-4">12. Transfers to Third Countries</h2>
        <ul className="list-disc list-inside mt-2">
         <li><strong>Within the EU/EEA: </strong>As a rule, we use data processors within the EU/EEA.</li>
         <li><strong>Outside the EU/EEA: </strong>In some cases, processors outside the EU/EEA may be used if they provide adequate protection for your personal data as required by law.</li>
        </ul>
      </section>
      
      <section>
        <h2 className="text-2xl font-bold mt-8 mb-4">13. Data Security</h2>
        <p>
        We take appropriate technical and organizational measures to protect your personal data against unauthorized or unlawful processing and accidental loss, destruction, or damage. Measures include:
        </p>
        <ul className="list-disc list-inside mt-2">
          <li>Regular risk assessments and implementation of security protocols.</li>
          <li>Ongoing employee training in GDPR and data protection practices.</li>
          <li>Continuous updates to our security procedures.</li>
        </ul>
        </section>
<br/>
        <section className="mb-6">
        <h2 className="text-2xl font-bold mb-4">14. Complaints</h2>
        <p>
        If you are dissatisfied with the way we handle your personal data, you have the right to lodge a complaint with the Danish Data Protection Authority (Datatilsynet) at <a href="https://www.datatilsynet.dk" className="text-blue-500">www.datatilsynet.dk</a>.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-bold mb-4">15. Changes to This Privacy Policy</h2>
        <p>
        We may update this Privacy Policy from time to time. Any changes will be posted on this page with an updated effective date. We encourage you to review this policy periodically.        </p>
      </section>

      <section>
        <h2 className="text-2xl font-bold mt-8 mb-4">16. Contact Information</h2>
        <p>
        If you have any questions or concerns about this Privacy Policy or our processing of your personal data, please contact us at:
        </p>
        <ul className="list-disc list-inside mt-2">
          <li><strong>Email:</strong> arunima@fendous.com</li>
          <li><strong>Phone:</strong> +45 29811860</li>
          <li><strong>Address:</strong> Valdermarsgade 8 1 TV, 9000 Aalborg, Denmark</li>
        </ul>
        <p>This Privacy Policy reflects our commitment to data protection and transparency. If you require further information, please reach out to us.</p>
        </section>
      </div>
    
  );
};
export default PrivacyPolicy;
